spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: zhixu2017
    url: jdbc:mysql://101.132.64.62/testdb3?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null
  redis:
    host: 192.168.30.113
    port: 6379
server:
  port: 8080